name: Sync Multi_Model_Streamlit to Hugging Face Space

on:
  push:
    paths:
      - 'ImageCaptioning_MultiModal/Multi_Model_Streamlit/**'  # Updated path

jobs:
  sync-streamlit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Configure Git
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "GitHub Actions Bot"
      - name: Sync to Hugging Face Space
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          cd ImageCaptioning_MultiModal/Multi_Model_Streamlit  # Updated path
          git init
          git branch -m main
          git remote add origin https://user:$HF_TOKEN@huggingface.co/spaces/NihalK/Multi_Model_Streamlit
          git add .
          git commit -m "Update Multi_Model_Streamlit"
          git push -f origin main
